import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SocketProvider from "@/components/SocketProvider";
import { AuthProvider } from "@/components/AuthProvider";
import { getServerMe } from "@/lib/auth-server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const me = await getServerMe();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={me}>
          <SocketProvider>
            {children}
          </SocketProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
